services:

  postgres:
    image: postgres:17
    container_name: meritum-postgres

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: meritum

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d meritum"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./Codigo/Backend

    container_name: meritum-backend

    ports:
      - "3333:3333"

    env_file:
      - ./Codigo/Backend/.env

    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/meritum?schema=public
      PORT: 3333
      HOST: 0.0.0.0

    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./Codigo/Backend:/app
      - /app/node_modules

    command: sh -c "npm run prisma:migrate && npm run prisma:seed && npm run dev"

  frontend:
    build:
      context: ./Codigo/Frontend

    container_name: meritum-frontend

    ports:
      - "5173:5173"

    environment:
      VITE_API_URL: http://localhost:3333

    depends_on:
      - backend

    volumes:
      - ./Codigo/Frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
